## Nornir Config File
---
inventory:
  plugin: NetBoxInventory2
  options:
    api_endpoint: https://192.168.12.114:8000
    api_token: "52acfb140685c3eeefe7d31038823cf52c5b4dfb"

runner:
  plugin: threaded
  options:
    num_workers: 20

