## Nornir Config File
---
inventory:
  plugin: NetBoxInventory2
  options:
    api_endpoint: https://netbox.local:8000
    api_token: "123456"

runner:
  plugin: threaded
  options:
    num_workers: 20

