# config.yaml
---
inventory:
  plugin: SimpleInventory
  options:
    host_file: '/home/kidscripto/Git/py-neng/nornir/inventory/hosts.yaml'
    group_file: '/home/kidscripto/Git/py-neng/nornir/inventory/groups.yaml'
    defaults_file: '/home/kidscripto/Git/py-neng/nornir/inventory/defaults.yaml'

#inventory:
#  plugin: NetBoxInventory2
#  options:
#    api_endpoint: "https://netbox.local:8000"
#    api_token: "f4e08aa5000e71f705e680e5add8f862bd187290"

runner:
  plugin: threaded
  options:
    num_workers: 20

